# Name: David McGuigan
# Student ID: 19425942
# I hereby acknowledge the DCU Academic Intergrity Policy

build: ../bin/myshell
	@true

../bin/myshell: myshell.c internalCmds.c utilities.c myshell.h
	gcc -o ../bin/myshell myshell.c internalCmds.c utilities.c

.PHONY: build
